import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Button, Card, Empty, Input, Loading, PageHeader } from '../components/ui'
import { addSubject, getAcademics, getSubjects, saveAcademic } from '../lib/data'
import { useAuth } from '../lib/auth'
import type { AcademicRecord, Subject } from '../lib/types'

export function AcademicsPage() {
  const { user } = useAuth(); const [records, setRecords] = useState<AcademicRecord[] | null>(null); const [subjects, setSubjects] = useState<Subject[] | null>(null); const [status, setStatus] = useState(''); const [academic, setAcademic] = useState({ semester: '', sgpa: '', cgpa: '' }); const [subject, setSubject] = useState({ semester: '', name: '', marks: '', completion: '0' })
  const refresh = () => { if (user) { getAcademics(user.id).then(setRecords).catch(e => setStatus(e.message)); getSubjects(user.id).then(setSubjects).catch(e => setStatus(e.message)) } }; useEffect(refresh, [user])
  if (!records || !subjects) return <Loading />
  const addRecord = async (e: FormEvent) => { e.preventDefault(); if (!user) return; try { await saveAcademic(user.id, { semester: Number(academic.semester), sgpa: academic.sgpa ? Number(academic.sgpa) : null, cgpa: academic.cgpa ? Number(academic.cgpa) : null }); setAcademic({ semester: '', sgpa: '', cgpa: '' }); refresh() } catch (error) { setStatus(error instanceof Error ? error.message : 'Could not save academic record.') } }
  const addNewSubject = async (e: FormEvent) => { e.preventDefault(); if (!user) return; try { await addSubject(user.id, { semester: Number(subject.semester), name: subject.name, marks: subject.marks ? Number(subject.marks) : null, completion: Number(subject.completion) }); setSubject({ semester: '', name: '', marks: '', completion: '0' }); refresh() } catch (error) { setStatus(error instanceof Error ? error.message : 'Could not add subject.') } }
  return <div className="page"><PageHeader eyebrow="YOUR ACADEMIC RECORD" title="Academics" /><div className="two-column"><Card title="CGPA / SGPA tracker"><form onSubmit={addRecord} className="form-grid three"><label>Semester<Input type="number" min="1" value={academic.semester} onChange={e => setAcademic({ ...academic, semester: e.target.value })} required /></label><label>SGPA<Input type="number" min="0" max="10" step="0.01" value={academic.sgpa} onChange={e => setAcademic({ ...academic, sgpa: e.target.value })} /></label><label>CGPA<Input type="number" min="0" max="10" step="0.01" value={academic.cgpa} onChange={e => setAcademic({ ...academic, cgpa: e.target.value })} /></label><Button>Add / update</Button></form><Records records={records} /></Card><Card title="Subject tracker"><form onSubmit={addNewSubject} className="form-grid"><label>Semester<Input type="number" min="1" value={subject.semester} onChange={e => setSubject({ ...subject, semester: e.target.value })} required /></label><label>Subject name<Input value={subject.name} onChange={e => setSubject({ ...subject, name: e.target.value })} required /></label><label>Marks (optional)<Input type="number" min="0" step="0.01" value={subject.marks} onChange={e => setSubject({ ...subject, marks: e.target.value })} /></label><label>Completion %<Input type="number" min="0" max="100" value={subject.completion} onChange={e => setSubject({ ...subject, completion: e.target.value })} required /></label><Button>Add subject</Button></form><Subjects items={subjects} /></Card></div>{status && <p className="form-message">{status}</p>}</div>
}
function Records({ records }: { records: AcademicRecord[] }) { if (!records.length) return <Empty title="No academic records yet" text="Add your actual SGPA or CGPA when you have it." />; return <div className="records">{records.map(r => <div key={r.id}><strong>Semester {r.semester}</strong><span>SGPA: {r.sgpa ?? '—'}</span><span>CGPA: {r.cgpa ?? '—'}</span></div>)}</div> }
function Subjects({ items }: { items: Subject[] }) { if (!items.length) return <Empty title="No subjects yet" text="Add subjects from your current or completed semesters." />; return <div className="subjects">{items.map(s => <div key={s.id}><div><strong>{s.name}</strong><span>Semester {s.semester} · Marks: {s.marks ?? '—'}</span></div><span>{s.completion}% complete</span><div className="progress"><i style={{ width: `${s.completion}%` }} /></div></div>)}</div> }
